### ISSUE TITLE
Error 56 - make install

### ISSUE THREAD

**Issue by esturniolo** [fmdlc/ISP-Checker#15]
Hi!
After ran `make install`, the scripts starts to download the images, etc. But at the end show this error:
```
Makefile:18: fallo en las instrucciones para el objetivo 'install'
make: *** [install] Error 56
```

It only works on a RPi? I'm trying to run in into an Ubuntu Server 20.04.

Full install log:
```
~/containers/ISP-Checker/ISP-Checker$ make install
Make: Creating persistent Docker volumes
Make: Initializing datasources and dashboards
Make: Bootstrap done
influxdb-storage
grafana-storage
Pulling influxdb (influxdb:1.8.3)...
1.8.3: Pulling from library/influxdb
0400ac8f7460: Pull complete
fa8559aa5ebb: Pull complete
da32bfbbc3ba: Pull complete
2107148596b1: Pull complete
db4f998976a3: Pull complete
6b778e6196d2: Pull complete
c32f0180a33f: Pull complete
b9b93617d021: Pull complete
Digest: sha256:08d4559f382b6f1705231a453b7a7e59f9387b8b37e825b8d4f815dfcfdd9b4b
Status: Downloaded newer image for influxdb:1.8.3
Pulling telegraf (tty0/isp_telegraf:1.15.3)...
1.15.3: Pulling from tty0/isp_telegraf
57df1a1f1ad8: Pull complete
71e126169501: Pull complete
1af28a55c3f3: Pull complete
ab2a2bd0ca59: Pull complete
f44285c3af7e: Pull complete
118995e564f1: Pull complete
5c07bdc503d4: Pull complete
b93e89ef41a7: Pull complete
50986952a7ee: Pull complete
Digest: sha256:3d2dd4b55fa1477b9eedfbdc1fd238c06593aa18ce96aa7ebf43d2248ede4e2d
Status: Downloaded newer image for tty0/isp_telegraf:1.15.3
Pulling grafana (grafana/grafana:7.2.1)...
7.2.1: Pulling from grafana/grafana
df20fa9351a1: Already exists
5f101b91128e: Pull complete
06b22e47f660: Pull complete
e8278dc77f35: Pull complete
4ac3c61790c9: Pull complete
e5505e948ec3: Pull complete
Digest: sha256:733842cca5bd9bcab1eb795da264863a8245402ff3ac8ff17e274334bb32c692
Status: Downloaded newer image for grafana/grafana:7.2.1
Creating influxdb ... 
Creating influxdb ... done
Creating telegraf ... 
Creating telegraf ... done
Creating grafana ... 
Creating grafana ... done
Makefile:18: fallo en las instrucciones para el objetivo 'install'
make: *** [install] Error 56
```

After that, I can reach http://ip:3000 and login with `admin - admin` and then change my password. But I can't see any dashboard inside Grafana.
I tried to import the `network-dashboard.json` file. Once imported the dashboard is empty.

And another final question: why you use `make` and not `docker-compose.yml` only?

**Comment by fmdlc** [comment]
Hi @esturniolo, thank you for the detailed report. I will take a look of this and let you know as soon as posible.

Regarding your lasted question, I'm using make to avoid building images for myself provisioning the dashboards and some standard configuration (like the Datasource). 

If you check the Makefile it does a few curl request against the Grafana API to provision the dashboard and also it's the reason because the manually import is not working for you, since the JSON dump is prepared to work with the API and not to be imported in the UI. For manual import please refer to: [https://grafana.com/grafana/dashboards/13140](https://grafana.com/grafana/dashboards/13140) 

Which cURL and make version do you have installed on your system?. 

Another thing I would like to try is removing the @ character on the curl commands. 

Could you execute it and paste the output here?.

Thank you!.

**Comment by esturniolo** [comment]
Ok with the existence of `Makefile`.

> Which cURL and make version do you have installed on your system?.
```
$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

> Could you execute it and paste the output here?.

Sure!
After delete the containers and volumes, the output for a new make install is:

```
$ make install
Make: Creating persistent Docker volumes
Make: Initializing datasources and dashboards
Make: Bootstrap done
influxdb-storage
grafana-storage
Creating influxdb ... 
Creating influxdb ... done
Creating telegraf ... 
Creating telegraf ... done
Creating grafana ... 
Creating grafana ... done
curl -s --location -X POST 'http://admin:admin@localhost:3000/api/datasources' \
	--header 'Content-Type: application/json' \
	-d @./grafana/datasource.json > /dev/null
Makefile:18: fallo en las instrucciones para el objetivo 'install'
make: *** [install] Error 56

```

**Comment by fmdlc** [comment]
This bug must be fixed with version `v1.3` released today.

**Comment by esturniolo** [comment]
Hi again.
Sorry to reopen this, but I still get the same error.

```
$ make install
Make: Creating persistent Docker volumes
Make: Initializing datasources and dashboards
Make: Bootstrap done
influxdb-storage
grafana-storage
Pulling influxdb (influxdb:1.8.3)...
1.8.3: Pulling from library/influxdb
0400ac8f7460: Pull complete
fa8559aa5ebb: Pull complete
da32bfbbc3ba: Pull complete
2107148596b1: Pull complete
db4f998976a3: Pull complete
6b778e6196d2: Pull complete
c32f0180a33f: Pull complete
b9b93617d021: Pull complete
Digest: sha256:08d4559f382b6f1705231a453b7a7e59f9387b8b37e825b8d4f815dfcfdd9b4b
Status: Downloaded newer image for influxdb:1.8.3
Pulling telegraf (tty0/isp_telegraf:1.15.3)...
1.15.3: Pulling from tty0/isp_telegraf
e4c3d3e4f7b0: Pull complete
101c41d0463b: Pull complete
8275efcd805f: Pull complete
b7d9d3d4ee2c: Pull complete
abe6b6309111: Pull complete
4f290c098c42: Pull complete
1cbbf75e5be7: Pull complete
248c498dda66: Pull complete
ce3d27808242: Pull complete
Digest: sha256:a3526a6477afb671106775d22106e2e8b7dc08b9630ee317ed0899173bd6db4b
Status: Downloaded newer image for tty0/isp_telegraf:1.15.3
Pulling grafana (grafana/grafana:7.2.1)...
7.2.1: Pulling from grafana/grafana
df20fa9351a1: Already exists
5f101b91128e: Pull complete
06b22e47f660: Pull complete
e8278dc77f35: Pull complete
4ac3c61790c9: Pull complete
e5505e948ec3: Pull complete
Digest: sha256:733842cca5bd9bcab1eb795da264863a8245402ff3ac8ff17e274334bb32c692
Status: Downloaded newer image for grafana/grafana:7.2.1
Creating influxdb ... 
Creating influxdb ... done
Creating telegraf ... 
Creating telegraf ... done
Creating grafana ... 
Creating grafana ... done
Unable to find image 'curlimages/curl:7.73.0' locally
7.73.0: Pulling from curlimages/curl
aad63a933944: Pulling fs layer
d47e05aac27c: Pulling fs layer
fd1e9b16f149: Pulling fs layer
4863971a917c: Pulling fs layer
6278c6418410: Pulling fs layer
0ad811736efa: Pulling fs layer
da1a9375412a: Pulling fs layer
77b6e91e3346: Pulling fs layer
ed8f8949fec1: Pulling fs layer
4863971a917c: Waiting
da1a9375412a: Waiting
0ad811736efa: Waiting
77b6e91e3346: Waiting
ed8f8949fec1: Waiting
fd1e9b16f149: Verifying Checksum
fd1e9b16f149: Download complete
d47e05aac27c: Verifying Checksum
d47e05aac27c: Download complete
aad63a933944: Download complete
4863971a917c: Download complete
0ad811736efa: Verifying Checksum
0ad811736efa: Download complete
aad63a933944: Pull complete
6278c6418410: Verifying Checksum
6278c6418410: Download complete
da1a9375412a: Verifying Checksum
da1a9375412a: Download complete
77b6e91e3346: Verifying Checksum
77b6e91e3346: Download complete
d47e05aac27c: Pull complete
ed8f8949fec1: Verifying Checksum
ed8f8949fec1: Download complete
fd1e9b16f149: Pull complete
4863971a917c: Pull complete
6278c6418410: Pull complete
0ad811736efa: Pull complete
da1a9375412a: Pull complete
77b6e91e3346: Pull complete
ed8f8949fec1: Pull complete
Digest: sha256:5329ee280d3d91f3e48885f18c884af5907b68c6aa80f411927a5a28c4f5df07
Status: Downloaded newer image for curlimages/curl:7.73.0
Makefile:18: fallo en las instrucciones para el objetivo 'install'
make: *** [install] Error 56
```

And then, the same behaviour:
I can connect to Grafana with admin-admin withpout problems, but the dashboard isn't there...

![image](https://user-images.githubusercontent.com/5169045/96589983-d82dda00-12bb-11eb-83fa-11399475af80.png)

Am I missing something?
There is some different log or something to try to help you with this?

**Comment by cerberus10** [comment]
Same issue here with the same version of Ubuntu 20.04 . Make log shows error 56 and the network dashboard is generated in grafana but now populated with any data even after 30 minutes.
